[project]
name = "iqm-research-award-2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "iqm-client[qiskit]>=35.0.0",
    "iqm-pulla[qiskit]>=14.0.0",
    "iqm-qubit-selector>=1.1.0",
    "matplotlib>=3.11.1",
    "mthree>=3.0.0",
]

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]


[tool.ruff]
line-length = 120
