"""
This script is used to gather and process job data from the IQM Sirius system.

It reads job summary data from a CSV file, which is generated by the job scheduling process,
and processes this data for further analysis or reporting. The script is typically run as
part of a batch processing pipeline to ensure up-to-date job information is available for
use in other modules or services.

The main function prints timestamps for when the script starts, when it begins gathering
jobs, and when it completes execution. This is useful for monitoring and debugging purposes.
"""

from datetime import datetime

from src.utils import gather_jobs

SYSTEM_NAME: str = "emerald"


def main() -> None:
    print(f"{datetime.now()}: Gathering jobs...")
    jobs_summary_path: str = "data/2026-08-19_023826_lg_jobs_summary.csv"
    gather_jobs(jobs_summary_path, SYSTEM_NAME)


if __name__ == "__main__":
    print(f"{datetime.now()}: Start")
    main()
    print(f"{datetime.now()}: Done")
